#!/bin/sh
set -e
if [ -x oohelper ]; then
  exit 0
fi
set -x
git clone https://github.com/ooni/probe-cli
cd probe-cli
git checkout 46e00888aea9bd398d590cef79b58be05878b079
go build -o ../oohelper ./internal/cmd/oohelper
cd ..
rm -rf probe-cli
