#!/usr/bin/env python3

"""
This script takes in input a single URL and shows its saved
measurement for both the old and the new TH.
"""

import json
import sqlite3
import sys


def main():
    "Main function."
    if len(sys.argv) != 3:
        sys.exit("usage: ./reprocess <config-file> <url>")
    config = json.load(open(sys.argv[1]))
    db = sqlite3.connect(config["database"])
    target_url = sys.argv[2]
    cursor = db.execute(
        "SELECT backend, json FROM results WHERE target = ?;", (target_url,)
    )
    for backend, jsondata in cursor:
        print(f"======= {target_url} @ {backend} =======")
        print("{}".format(json.dumps(json.loads(jsondata), indent=2)))


if __name__ == "__main__":
    main()
