#!/usr/bin/env python3

"""
This script removes entries from the DB specified in the input
config file and matching a specific category.

For example:

    ./reprocess config-7.json "dns/mismatch/new_data_none_addrs"

Will remove from the database specified inside config-7.json
all the URLs classified with the specified dns/mismatch category.

To figure out the URLs that matches this category, this script
will use the stats DB mentioned into the config file.
"""

import json
import sqlite3
import sys


def main():
    "Main function."
    if len(sys.argv) != 3:
        sys.exit("usage: ./reprocess <config-file> <category>")
    config = json.load(open(sys.argv[1]))
    stats = sqlite3.connect(config["stats"])
    cursor = stats.execute("SELECT key, url FROM stats WHERE key = ?;", (sys.argv[2],))
    with sqlite3.connect(config["database"]) as db:
        for url in (url[1] for url in cursor):
            print(f"deleting {url}", file=sys.stderr)
            db.execute("DELETE FROM results WHERE target = ?;", (url,))


if __name__ == "__main__":
    main()
