#!/usr/bin/env python3

"""
This script removes a single URL from the database specified in
the config file.

For example:

    ./reprocessurl config-7.json "http://example.com"

Will remove from the database specified inside config-7.json
the "http://example.com" URL.
"""

import json
import sqlite3
import sys


def main():
    "Main function."
    if len(sys.argv) != 3:
        sys.exit("usage: ./reprocess <config-file> <url>")
    config = json.load(open(sys.argv[1]))
    url = sys.argv[2]
    with sqlite3.connect(config["database"]) as db:
        print(f"deleting {url}", file=sys.stderr)
        db.execute("DELETE FROM results WHERE target = ?;", (url,))


if __name__ == "__main__":
    main()
