#!/usr/bin/env python3

"""
This script shows you all the URLs inside a category. In this context
category is the name of a set of differences between the old and the
new Web Connectivity Test Helpers.

Example:

    ./showcategory config-7.json "dns/mismatch/other"

This will read all the URLs inside the stats DB associated with
config-7.json and will print them one by one.
"""

import json
import sqlite3
import sys


def main():
    "Main function."
    if len(sys.argv) != 3:
        sys.exit("usage: ./reprocess <config-file> <category>")
    config = json.load(open(sys.argv[1]))
    stats = sqlite3.connect(config["stats"])
    cursor = stats.execute("SELECT key, url FROM stats WHERE key = ?;", (sys.argv[2],))
    for url in (url[1] for url in cursor):
        print(f"{url}", file=sys.stderr)


if __name__ == "__main__":
    main()
